default:
  cachePath: '../cache/'
  latestChangeUrl: 'http://poe.ninja/api/Data/GetStats'
  changeIdField: 'next_change_id'
  retention:
    interval: 5
    unit: minutes
production:
  retention:
    interval: 6
    unit: hours
