default:
  host: http://localhost:9200
  batchSize: 1000
  timeout:
    interval: 120
    unit: seconds
beta:
  batchSize: 100
production:
  host: http://phreak.space:9200
  timeout:
    interval: 180
