default:
  scoring:
    sort:
      - lastSeen:
          order: 'asc'
      - firstSeen:
          order: 'asc'
    query:
      bool:
        must:
          - match:
              removed: false
          - match:
              rarity: 'Rare'
          - match:
              itemType: 'Gear'
          - match:
              'meta.quality': 0
  unscoring:
    query:
      bool:
        must:
          - match:
              removed: false
          - match:
              rarity: 'Rare'
          - match:
              itemType: 'Gear'
          - range:
              'meta.quality':
                gt: 0

