default:
  delay:
    interval: 5
    unit: seconds
  retention:
    interval: 1
    unit: hours
  elastic:
    host: http://localhost:9200
    logLevel: error
    dataShard: poe-data
    leagueShard: poe-league
