default:
  api:
    uri: http://api.pathofexile.com/public-stash-tabs
  process:
    concurrency: 2
    interval: 5
    unit: seconds
  fetch:
    concurrency: 2
    interval: 5
    unit: seconds
  cache:
    maxSizeMb: 30
    delay:
      interval: 1
      unit: seconds
  retention:
    stash:
      interval: 30
      unit: days
    listing:
      interval: 7
      unit: days
