default:
  stashTabUrl: 'http://betaapi.pathofexile.com/api/public-stash-tabs'
  index:
    interval:
      concurrency: 1
      interval: 5
      unit: seconds
  retention:
    stash:
      interval: 7
      unit: days
    listing:
      interval: 2
      unit: days
production:
  retention:
    stash:
      interval: 30
      unit: days
    listing:
      interval: 7
      unit: days
