default:
  process:
    concurrency: 2
    interval: 2
    unit: seconds
  fetch:
    concurrency: 2
    interval: 10
    unit: seconds
  retention:
    stash:
      interval: 30
      unit: days
    listing:
      interval: 7
      unit: days
