default:
  process:
    concurrency: 1
    interval: 5
    unit: seconds
  fetch:
    concurrency: 2
    interval: 5
    unit: seconds
  retention:
    stashes:
      interval: 30
      unit: days
    listings:
      interval: 7
      unit: days
