default:
  process:
    concurrency: 1
    interval: 1
    unit: seconds
  fetch:
    concurrency: 2
    interval: 8
    unit: seconds
  retention:
    stash:
      interval: 30
      unit: days
    listing:
      interval: 7
      unit: days
