default:
  process:
    concurrency: 2
    interval: 1
    unit: seconds
  fetch:
    concurrency: 2
    interval: 5
    unit: seconds
  retention:
    stash:
      interval: 7
      unit: days
    listing:
      interval: 2
      unit: days
production:
  retention:
    stash:
      interval: 30
      unit: days
    listing:
      interval: 7
      unit: days
