default:
  stashTabUrl: 'http://www.pathofexile.com/api/public-stash-tabs'
  download:
    concurrency: -1 # unlimited
    interval:
      value: 2
      unit: seconds
  index:
    concurrency: 1 # one at a time to preserve order
    interval:
      value: 1
      unit: seconds
  retention:
    stash:
      interval: 7
      unit: days
    listing:
      interval: 2
      unit: days
production:
  retention:
    stash:
      interval: 30
      unit: days
    listing:
      interval: 7
      unit: days
