default:
  hostname: localhost
  port: 3000
  socket: 3030
  emit:
    delay:
      interval: 5
      unit: seconds
production:
  hostname: poe-sniper.com
  port: 80
  socket: 8080
  emit:
    delay:
      interval: 15
      unit: seconds
